# Generated by Django 4.1.4 on 2023-01-14 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('threshold', models.IntegerField(default=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='exxon-mobile', max_length=200)),
                ('number_risk_statements', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='exxon-mobile', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_date', models.DateTimeField(default=datetime.datetime(2022, 10, 6, 0, 34, 57, 481047, tzinfo=datetime.timezone.utc))),
                ('to_date', models.DateTimeField(default=datetime.datetime(2023, 1, 14, 0, 34, 57, 481091, tzinfo=datetime.timezone.utc))),
                ('threshold', models.IntegerField(default=5)),
                ('number_risk_articles', models.IntegerField(default=0)),
                ('phrases', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(to='instance.article')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
