# Generated by Django 4.1.4 on 2023-01-14 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 4, 26, 43, 499515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='instance',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 4, 26, 43, 499528, tzinfo=datetime.timezone.utc)),
        ),
    ]
